"""
SmartPoli — what to do next, after the triage rules have spoken.

Guidance is never generated by the LLM. It comes from two places only:
  1. the patient's OWN record — as-needed medicines their doctor prescribed
     (always listed first, with the instruction as written), and
  2. self_care.json — short general self-care steps, each with its source
     and the severity levels it applies to.

Nothing here names a new medicine. Breathing and chest-pain symptoms get no
home-care steps at all. EMERGENCY gets no guidance and no recheck: that
patient needs medical help, not a self-care trial.
"""

import json
import os
from typing import Optional

_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "self_care.json")
with open(_PATH, encoding="utf-8") as f:
    SELF_CARE = json.load(f)

DEFAULT_RECHECK_MINUTES = 15


def guidance_for(symptom_ids: list[str], severity: str, lang: str, prescribed: list[dict]) -> dict:
    """`prescribed`: [{name, instruction}] from the patient's record."""
    if severity == "EMERGENCY":
        return {"prescribed": [], "general": [], "recheck_minutes": None}

    general, seen = [], set()
    recheck: Optional[int] = DEFAULT_RECHECK_MINUTES if not symptom_ids else None
    for sid in symptom_ids:
        entry = SELF_CARE["symptoms"].get(sid, {"recheck_minutes": DEFAULT_RECHECK_MINUTES, "items": []})
        minutes = entry.get("recheck_minutes")
        if minutes is not None:
            recheck = minutes if recheck is None else min(recheck, minutes)
        for item in entry["items"]:
            text = item.get(lang) or item["en"]
            if severity in item["levels"] and text not in seen:
                seen.add(text)
                source = SELF_CARE["sources"][item["source"]]
                general.append({"text": text, "source_title": source["title"], "source_url": source["url"]})
    # A symptom with no safe home-care (chest pain) means no "wait and see" for the whole check.
    if any(SELF_CARE["symptoms"].get(sid, {}).get("recheck_minutes", 0) is None for sid in symptom_ids):
        recheck = None
    return {"prescribed": list(prescribed), "general": general, "recheck_minutes": recheck}
