"""
SmartPoli — .ics calendar export (Part 8 of the brief).

Turns the EXISTING medication schedule (Dose rows, generated once at
confirmation — CLAUDE.md invariant 1) into a standard iCalendar feed. This
is not a second scheduler: it only reads Dose rows that already exist and
formats them as VEVENTs. A minimal, hand-rolled RFC 5545 writer — the
format is small enough that a dependency for it isn't worth adding.
"""

from datetime import timedelta
from typing import Iterable

from db import Dose, Medicine

_STATE_LABEL = {
    "pending": "Upcoming", "snoozed": "Snoozed", "taken": "Taken",
    "missed": "Missed", "skipped": "Skipped",
}

EVENT_DURATION = timedelta(minutes=15)


def _escape(text: str) -> str:
    return (text or "").replace("\\", "\\\\").replace(",", "\\,").replace(";", "\\;").replace("\n", "\\n")


def _fold(line: str) -> str:
    """RFC 5545 75-octet line folding. Most calendar apps tolerate long
    unfolded lines, but folding is cheap and keeps this spec-correct."""
    if len(line) <= 75:
        return line
    parts = [line[:75]]
    rest = line[75:]
    while rest:
        parts.append(" " + rest[:74])
        rest = rest[74:]
    return "\r\n".join(parts)


def build_ics(medicines_with_doses: Iterable[tuple[Medicine, list[Dose]]], now_stamp: str) -> bytes:
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//SmartPoli//Medication Schedule//EN",
        "CALSCALE:GREGORIAN",
    ]
    for medicine, doses in medicines_with_doses:
        name = medicine.name or medicine.raw_text
        for dose in doses:
            dt_start = dose.scheduled_at.strftime("%Y%m%dT%H%M%S")
            dt_end = (dose.scheduled_at + EVENT_DURATION).strftime("%Y%m%dT%H%M%S")
            summary = f"{name} — {_STATE_LABEL.get(dose.state, dose.state)}"
            desc_parts = []
            if medicine.dose_amount:
                desc_parts.append(f"Dose: {medicine.dose_amount}{medicine.dose_unit or ''}")
            if medicine.food and medicine.food != "any":
                desc_parts.append(f"Take {medicine.food} food.")
            desc_parts.append("Generated by SmartPoli. Assistive tool, not a medical device.")
            lines += [
                "BEGIN:VEVENT",
                f"UID:smartpoli-dose-{dose.id}@smartpoli",
                f"DTSTAMP:{now_stamp}",
                f"DTSTART:{dt_start}",
                f"DTEND:{dt_end}",
                _fold(f"SUMMARY:{_escape(summary)}"),
                _fold(f"DESCRIPTION:{_escape(' | '.join(desc_parts))}"),
                "END:VEVENT",
            ]
    lines.append("END:VCALENDAR")
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")
